GET http://localhost:3333/controle_lote

###

GET http://localhost:3333/controle_lote/12

###

POST http://localhost:3333/controle_lote
Content-Type: application/json

{
    "produto_lote_id": 4,
    "lote": "ABC123",
    "quantidade":  "10",
    "data_validade": "2024-06-21"
}


###

PUT http://localhost:3333/controle_lote/atualizar/2
Content-Type: application/json

{
    "produto_lote_id": "4"
}

###

DELETE http://localhost:3333/controle_lote/excluir/12