GET http://localhost:3333/cidade

###

GET http://localhost:3333/cidade/1

###

POST http://localhost:3333/cidade
Content-Type: application/json

{
    "nome_cidade": "Terra Rica",
    "estado_cidade_id": 1
}


###

PUT http://localhost:3333/cidade/atualizar/2
Content-Type: application/json

{
    "nome_cidade": "Rio de Janeiro"
}

###

DELETE http://localhost:3333/cidade/excluir/2