GET http://localhost:3333/usuario

###

GET http://localhost:3333/usuario/4

###

POST http://localhost:3333/usuario
Content-Type: application/json

{
    "nome": "Caroline Mazutti",
    "login_user": "Carol",
    "senha_user": "123",
    "perfil": "gerente"
}


###

PUT http://localhost:3333/usuario/atualizar/10
Content-Type: application/json

{
    "nome": "Carol"
}

###

DELETE http://localhost:3333/usuario/excluir/7